package base

const BucketPrefix = "master."
const BucketAggregate = BucketPrefix + "aggregate"
const BucketProduct = BucketPrefix + "product"
const BucketDevice = BucketPrefix + "device"
const BucketProject = BucketPrefix + "project"
const BucketSpace = BucketPrefix + "space"
const BucketHistory = BucketPrefix + "history"
const BucketGateway = BucketPrefix + "gateway"
const BucketScene = BucketPrefix + "scene"
const BucketTimer = BucketPrefix + "timer"
const BucketValidator = BucketPrefix + "validator"
const BucketAlarm = BucketPrefix + "alarm"
const BucketAction = BucketPrefix + "action"
